ragflow:
  host: 0.0.0.0
  http_port: 9380
admin:
  host: 0.0.0.0
  http_port: 9381
mysql:
  name: 'rag_flow'
  user: 'root'
  password: 'infini_rag_flow'
  host: 'localhost'
  port: 5455
  max_connections: 900
  stale_timeout: 300
  max_allowed_packet: 1073741824
minio:
  user: 'rag_flow'
  password: 'infini_rag_flow'
  host: 'localhost:9000'
es:
  hosts: 'http://localhost:1200'
  username: 'elastic'
  password: 'infini_rag_flow'
os:
  hosts: 'http://localhost:1201'
  username: 'admin'
  password: 'infini_rag_flow_OS_01'
infinity:
  uri: 'localhost:23817'
  db_name: 'default_db'
oceanbase:
  scheme: 'oceanbase' # set 'mysql' to create connection using mysql config
  config:
    db_name: 'test'
    user: 'root@ragflow'
    password: 'infini_rag_flow'
    host: 'localhost'
    port: 2881
redis:
  db: 1
  password: 'infini_rag_flow'
  host: 'localhost:6379'
task_executor:
  message_queue_type: 'redis'
user_default_llm:
  default_models:
    embedding_model:
      name: BAAI/bge-small-en-v1.5@FastEmbed
      api_key: 'xxx'
      base_url: 'http://localhost:6380'
