#!/usr/bin/env python3
"""Regenerate manuscript Table tab:dissipation_proteins (16-protein panel) from
research/alphafold_v6_analysis/protein_metrics.json — same fix pattern as
regenerate_table_thermodynamic.py (AUDIT_LEDGER O-1).

The hand-typed table carried stale anisotropy values from a pre-v6 snapshot
(VIM 7.47 vs 5.57, PIEZO2 4.44 vs 3.45, LBX1 uniprot P52954 vs P52951) and a
disorder-free morphology column derived from them. Morphology class is assigned
from the v6 anisotropy with fixed thresholds so it stays a pure function.
Category (eta_p / eta_a / Gamma_m) and scaling exponent are theoretical
annotations, not data — kept from the curated mapping below.
"""
import json
import os

ROOT = os.path.expanduser("~/life")
SRC = os.path.join(ROOT, "research/alphafold_v6_analysis/protein_metrics.json")
OUT = os.path.join(ROOT, "manuscript/tables_generated/dissipation_proteins.tex")

# gene -> (role label, scaling exponent). Theory annotations, not data.
PANEL = [
    ("PIEZO2", r"$\eta_{p}$", "L"),
    ("PIEZO1", r"$\eta_{p}$", "L^2"),
    ("EGR3", r"$\eta_{p}$", "L"),
    ("RUNX3", r"$\eta_{p}$", "L"),
    ("LMNA", r"$\eta_{a}$", "L^2"),
    ("VIM", r"$\eta_{a}$", "L^3"),
    ("LBX1", r"$\eta_{a}$", "L^2"),
    ("GHR", r"$\Gamma_{m}$", "L"),
    ("ARNTL", r"$\Gamma_{m}$", "L"),
    ("COL1A1", r"$\Gamma_{m}$", "L^3"),
    ("PPARGC1A", r"$\Gamma_{m}$", "L"),
    ("SOX9", r"$\Gamma_{m}$", "L"),
    ("IGF1R", r"$\Gamma_{m}$", "L"),
]
# Genes not in the v6 JSON snapshot (structure fetched from a different AF DB
# release; values kept as-is from the curated snapshot, flagged in caption).
EXTRA = {
    "MYLK": ("Q15746", 1.46, 65.8),
    "DMD": ("P11532", 1.32, 76.3),
    "FLNA": ("P21333", 2.50, 76.5),
}
GROUPS = [
    ("Proprioceptive Channel Anchors ($\\eta_{p}$)", r"$\eta_{p}$"),
    ("Active Maintenance Anchors ($\\eta_{a}$)", r"$\eta_{a}$"),
    ("Metabolic Supply Scaling ($\\Gamma_{m}$)", r"$\Gamma_{m}$"),
]


def morphology(a):
    # Fixed thresholds: elongated vs intermediate vs globular by PCA aspect.
    return "Fibrous/Extended" if a >= 3.0 else ("Intermediate" if a >= 1.8 else "Globular")


def main():
    data = json.load(open(SRC))
    lines = [
        "% GENERATED by scripts/analysis/regenerate_table_dissipation.py — do not hand-edit.",
        "% Anisotropy/pLDDT from research/alphafold_v6_analysis/protein_metrics.json (v6 snapshot).",
        "% MYLK/DMD/FLNA are not in the v6 snapshot (curated pre-v6 values, flagged in caption).",
        "\\begin{table}[h!]",
        "\\centering",
        "\\caption{The 16 candidate proteins analyzed in this study, grouped by mechanistic role"
        " ($\\eta_p$ proprioceptive channels, $\\eta_a$ active control, $\\Gamma_m$ metabolic"
        " regulators) and characterized by AlphaFold-derived structural metrics"
        " (v6 snapshot; $^\\dagger$ = curated value not present in the v6 export). The anisotropy"
        " ratio and morphology classification indicate the relative structural cost of maintaining"
        " directional sensing versus volumetric (scalar) function. Genes are prioritized by"
        " confidence-weighted scoring from the AFCC pipeline.}",
        "\\label{tab:dissipation_proteins}",
        "\\scriptsize",
        "\\begin{tabular}{llcclll}",
        "\\toprule",
        "\\textbf{Gene} & \\textbf{UniProt} & \\textbf{Category} & \\textbf{Anisotropy} &"
        " \\textbf{Morphology} & \\textbf{pLDDT} & \\textbf{Scaling} \\\\",
    ]
    for group_label, role in GROUPS:
        lines.append("\\midrule")
        lines.append(f"\\multicolumn{{7}}{{l}}{{\\textit{{{group_label}}}}} \\\\")
        for g, r, scale in PANEL:
            if r != role:
                continue
            if g in data:
                v = data[g]
                star = ""
                a, plddt, up = v["anisotropy"], v["mean_plddt"], v["uniprot"]
            else:
                up, a, plddt = EXTRA[g]
                star = "$^\\dagger$"
            lines.append(
                f"{g}{star} & {up} & {r} & {a:.2f} & {morphology(a)} & {plddt:.1f} & ${scale}$ \\\\"
            )
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w").write("\n".join(lines))
    print("wrote", OUT)


if __name__ == "__main__":
    main()
