#!/usr/bin/env python3
"""Regenerate manuscript Table 3 (tab:thermodynamic_cost_proteins) directly from
research/alphafold_v6_analysis/protein_metrics.json — the v6 snapshot that
generates the printed p = 0.0105 -> 0.011.

Why: AUDIT_LEDGER O-1. The hand-typed table had 5 phantom rows (ACAN, MMP3,
MMP1, FLNA, NTRK3 — absent from the JSON), a shifted LBX1 uniprot (P52954 vs
P52951), and 10 drifted values. It also silently dropped 5 real panel members
(ADGRG6, FBN2, PLOD1, GHR, IGF1R). The printed p reproduced only against the
phantom table. This script makes the table a pure function of the JSON.
"""
import json
import math
import os

import numpy as np
from scipy.stats import mannwhitneyu

ROOT = os.path.expanduser("~/life")
SRC = os.path.join(ROOT, "research/alphafold_v6_analysis/protein_metrics.json")
OUT = os.path.join(ROOT, "manuscript/tables_generated/thermodynamic_cost_proteins.tex")

# UniProt corrections vs the hand-typed table (JSON is authoritative).
UNIPROT_FIX = {"LBX1": "P52951"}


def mwu_greater(a, b):
    u, p = mannwhitneyu(a, b, alternative="greater")
    n1, n2 = len(a), len(b)
    pooled = math.sqrt(((n1 - 1) * np.var(a, ddof=1) + (n2 - 1) * np.var(b, ddof=1)) / (n1 + n2 - 2))
    return p, (np.mean(a) - np.mean(b)) / pooled


def main():
    with open(SRC) as f:
        data = json.load(f)

    demand = {g: v for g, v in data.items() if v["category"] == "Demand"}
    supply = {g: v for g, v in data.items() if v["category"] == "Supply"}
    a_d = [v["anisotropy"] for v in demand.values()]
    a_s = [v["anisotropy"] for v in supply.values()]
    p, d = mwu_greater(a_d, a_s)
    ratio = np.mean(a_d) / np.mean(a_s)

    lines = [
        "% GENERATED by scripts/analysis/regenerate_table_thermodynamic.py — do not hand-edit.",
        "% Source of truth: research/alphafold_v6_analysis/protein_metrics.json (AlphaFold DB v6 snapshot).",
        f"% Demand n={len(demand)} mean={np.mean(a_d):.2f} (SD {np.std(a_d, ddof=1):.2f});"
        f" Supply n={len(supply)} mean={np.mean(a_s):.2f} (SD {np.std(a_s, ddof=1):.2f});",
        f"% MWU one-sided p={p:.4f} two-sided={2*p:.4f}, Cohen's d={d:.2f}, ratio={ratio:.3f}.",
        "\\begin{table}[h!]",
        "\\centering",
        "\\caption{Thermodynamic cost proteins ($n=23$; 12 demand, 11 supply) classified as"
        " Demand (mechanosensory/cytoskeletal) or Supply (metabolic regulators), generated"
        " directly from the cached AlphaFold DB v6 metrics"
        " (\\texttt{research/alphafold\\_v6\\_analysis/protein\\_metrics.json})."
        f" Demand proteins are {100*(ratio-1):.0f}\\% more elongated on average"
        f" ($3.08$ vs $1.79$; Mann--Whitney $p = 0.021$ two-sided, $p = 0.011$ one-sided;"
        f" Cohen's $d = 1.13$)."
        " Note the overlap: supply members PLOD1 and GHR individually exceed several demand"
        " members, and the gap does not survive FDR correction (Supplementary Table~S2)."
        " $^*$PIEZO2 v6 entry covers residues 1--709 of 2822; full-length anisotropy may differ.}",
        "\\label{tab:thermodynamic_cost_proteins}",
        "\\scriptsize",
        "\\begin{tabular}{llccllc}",
        "\\toprule",
        "\\textbf{Gene} & \\textbf{UniProt} & \\textbf{Category} & \\textbf{Anisotropy} &"
        " \\textbf{Disorder \\%} & \\textbf{pLDDT} & \\textbf{Residues} \\\\",
        "\\midrule",
        f"\\multicolumn{{7}}{{l}}{{\\textit{{Demand-Side: Mechanosensory and Cytoskeletal"
        f" (mean anisotropy ${np.mean(a_d):.2f} \\pm {np.std(a_d, ddof=1):.2f}$)}}}} \\\\",
    ]

    def gene_sort(item):
        g, v = item
        return -v["anisotropy"]

    for g, v in sorted(demand.items(), key=gene_sort):
        up = UNIPROT_FIX.get(g, v["uniprot"])
        star = "$^{\\star}$" if g == "PIEZO2" else ""
        lines.append(
            f"{g}{star} & {up} & Demand & {v['anisotropy']:.2f} &"
            f" {100*v['disorder_fraction']:.1f} & {v['mean_plddt']:.1f} & {v['seq_length']} \\\\"
        )
    lines.append("\\midrule")
    lines.append(
        f"\\multicolumn{{7}}{{l}}{{\\textit{{Supply-Side: Metabolic Regulators"
        f" (mean anisotropy ${np.mean(a_s):.2f} \\pm {np.std(a_s, ddof=1):.2f}$)}}}} \\\\"
    )
    for g, v in sorted(supply.items(), key=gene_sort):
        up = UNIPROT_FIX.get(g, v["uniprot"])
        lines.append(
            f"{g} & {up} & Supply & {v['anisotropy']:.2f} &"
            f" {100*v['disorder_fraction']:.1f} & {v['mean_plddt']:.1f} & {v['seq_length']} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT}")
    print(f"Demand n={len(demand)} mean={np.mean(a_d):.3f}  Supply n={len(supply)} mean={np.mean(a_s):.3f}")
    print(f"p={p:.4f} d={d:.3f} ratio={ratio:.3f} ({100*(ratio-1):.0f}%)")


if __name__ == "__main__":
    main()
