import pandas as pd
import sys
import numpy as np

def downsample_data():
    input_path = "outputs/thermodynamic_cost/phase_diagram_energy_deficit.csv"
    output_path = "outputs/thermodynamic_cost/phase_diagram_energy_deficit_downsampled.csv"

    try:
        df = pd.read_csv(input_path)
    except FileNotFoundError:
        print(f"Error: {input_path} not found.")
        sys.exit(1)

    # The data is generated by looping chi_kappa (outer) then L (inner).
    # Both have 20 values.
    # We want to downsample to a 5x5 grid.

    # Unique values
    chi_vals = df['chi_kappa'].unique()
    L_vals = df['L'].unique()

    if len(chi_vals) != 20 or len(L_vals) != 20:
        print(f"Warning: Expected 20x20 grid, found {len(chi_vals)}x{len(L_vals)}. Proceeding with simple slicing.")
        # Fallback
        df_downsampled = df.iloc[::16].reset_index(drop=True)
    else:
        # Sort just in case
        df = df.sort_values(by=['chi_kappa', 'L'])

        # Reshape indices
        # We want indices 0, 4, 8, 12, 16 for both dimensions.
        indices = []
        for i in range(0, 20, 4): # chi indices
            for j in range(0, 20, 4): # L indices
                # Row index in flattened df
                idx = i * 20 + j
                indices.append(idx)

        df_downsampled = df.iloc[indices].reset_index(drop=True)

    # Save
    df_downsampled.to_csv(output_path, index=False)
    print(f"Saved downsampled data to {output_path} with {len(df_downsampled)} rows.")

if __name__ == "__main__":
    downsample_data()
